---
- name: systemd_helper | Deploy timesyncd.conf
  template:
    src: "timesyncd.j2"
    dest: "/etc/systemd/timesyncd.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
  - "Restart systemd-timesyncd"
- name: systemd_helper | Enable systemd-timesyncd service
  systemd:
    name: "systemd-timesyncd"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['systemd_timesyncd'] |
     json_query(vars['systemd_timesyncd_enable']) is defined"
  - "hostvars[inventory_hostname]['systemd_timesyncd'] |
     json_query(vars['systemd_timesyncd_enable']) == 'true'"
  vars:
    systemd_timesyncd_enable: "[] | map(&enable || 'false', @) | [0]"
